const humanPermissions = {
	createinstantinvite: 'Create Invites',
	kickmembers: 'Kick Members',
	banmembers: 'Ban Members',
	managechannels: 'Manage Channels',
	manageguild: 'Manage Guild',
	addreactions: 'Add Reactions',
	viewauditlog: 'View Audit Log',
	priorityspeaker: 'Priority Speaker',
	stream: 'Stream',
	viewchannel: 'View Channels',
	sendmessages: 'Send Messages',
	sendttsmessages: 'Send TTS',
	managemessages: 'Manage Messages',
	embedlinks: 'Embed Links',
	attachfiles: 'Attach Files',
	readmessagehistory: 'Read Message History',
	mentioneveryone: 'Mention Everyone',
	useexternalemojis: 'Use External Emojis',
	viewguildinsights: 'View Guild Insights',
	connect: 'Connect',
	speak: 'Speak',
	mutemembers: 'Mute Members',
	deafenmembers: 'Deafen Members',
	movemembers: 'Move Members',
	usevad: 'Use Voice Activity',
	changenickname: 'Change Nickname',
	managenicknames: 'Manage Nicknames',
	manageroles: 'Manage Roles',
	managewebhooks: 'Manage Webhooks',
	manageemojisandstickers: 'Manage Emojis & Stickers',
	manageguildexpressions: 'Manage Expressions',
	useapplicationcommands: 'Use Application Commands',
	requesttospeak: 'Request to Speak',
	manageevents: 'Manage Events',
	managethreads: 'Manage Threads',
	createpublicthreads: 'Create Public Threads',
	createprivatethreads: 'Create Private Threads',
	useexternalstickers: 'Use External Stickers',
	sendmessagesinthreads: 'Send Messages in Threads',
	useembeddedactivities: 'Use Embedded Activites',
	moderatemembers: 'Moderate Members',
	viewcreatormonetizationanalytics: 'View Creator Monetization Analytics',
	usesoundboard: 'Use Soundboard',
	useexternalsounds: 'Use External Sounds',
	sendvoicemessages: 'Send Voice Messages',
};

module.exports = {
	humanPermissions,
};
