module.exports = {
	Guild: require('./schemas/guild'),
	botData: require('./schemas/botData'),
	userData: require('./schemas/userData'),
	Level: require('./schemas/levelSchema'),
	levelRoles: require('./schemas/levelRoles'),
	pollData: require('./schemas/pollData'),
	pollVoterData: require('./schemas/pollVoterData'),
	reminderData: require('./schemas/reminderData'),
	giveawaysData: require('./schemas/giveawayData'),
	starboardData: require('./schemas/starboardData'),
	youtubeNotificationData: require('./schemas/youtubeNotificationData'),
	roleAssignmentData: require('./schemas/roleAsignmentData'),
	autoChannelData: require('./schemas/autoChannelData'),
};
